#!/bin/bash
########################################################################################
# SUSE Enterprise Storage 5\6, Script to list pools and pg/pgp values.
SVER='1.00-001'
SDATE="2019 10 08"
#
# Description:
# Simple script to list pools and pg/pgp values.
# Run on the admin node.
#
########################################################################################

LIST=$(ceph osd pool ls)
#echo $LIST
for i in $LIST; do
  PG_NUM=$(ceph osd pool get $i pg_num)
  PGP_NUM=$(ceph osd pool get $i pgp_num)
  echo "Pool:  $i"
  echo "       $PG_NUM"
  echo "       $PGP_NUM"
  echo
done
