#!/bin/bash

# Simple script to list pools and pg/pgp values.
# Run on the admin node.

LIST=$(ceph osd lspools | sed 's/[0-9]*//g' | sed 's/,*//g')
#echo $LIST
for i in $LIST; do
  PG_NUM=$(ceph osd pool get $i pg_num)
  PGP_NUM=$(ceph osd pool get $i pgp_num)
  echo "Pool:  $i"
  echo "       $PG_NUM"
  echo "       $PGP_NUM"
  echo
done
