#!/bin/bash
echo ""
printf "%-20s %-8s %-9s %-16s %-16s %-8s %-8s %-15s\n" "Pool" "Size/Min" "PG/PGP" "Crush Rule" "EC Profile" "K/M" "APP" "Root Bucket"

POOLLIST=$(ceph osd pool ls)
for POOL in $POOLLIST; do
  POOLINFO=$(ceph osd pool get $POOL all)
  SIZE=$(echo $POOLINFO  | cut -d " " -f2)
  MSIZE=$(echo $POOLINFO  | cut -d " " -f4)
  PG=$(echo $POOLINFO  | cut -d " " -f8)
  PGP=$(echo $POOLINFO  | cut -d " " -f10)
  RULE=$(echo $POOLINFO  | cut -d " " -f12)
  ECPROFILE=$(echo $POOLINFO  | cut -d " " -f34)
  RULEINFO=$(ceph osd crush rule dump $RULE)
  RULETYPE=$(echo $RULEINFO | cut -d " " -f9 | sed 's/[^a-zA-Z0-9]//g')
  if [ $RULETYPE = 3 ]; then
    PROFILEINFO=$(ceph osd erasure-code-profile get $ECPROFILE)
    K=$(echo $PROFILEINFO | cut -d " " -f5)
    M=$(echo $PROFILEINFO | cut -d " " -f6)
  fi
  APP=$(ceph osd pool application get iscsi-images | tail -n +2 | head -n1 | sed 's/[^a-zA-Z0-9]//g')
  BUCKET=$(ceph osd crush rule dump $RULE | grep item_name | cut -d " " -f14 | sed 's/[^a-zA-Z0-9~]//g')
  printf "%-20s %-8s %-9s %-16s %-16s %-8s %-8s %-15s\n" "$POOL" "$SIZE/$MSIZE" "$PG/$PGP" "$RULE" "$ECPROFILE" "$K $M" "$APP" "$BUCKET"
done
