#!/bin/bash
########################################################################################
# SUSE Enterprise Storage 5, Script to list deep+scrubbing by day and hour.
SVER='1.00-000'
SDATE="2019 06 18"
#
# Description:
# Run on the admin node.
#
# "ceph pg dump"
# columns 20 & 21 are scrub history
# columns 23 & 24 are for deep-scrub history
########################################################################################
echo
echo "=============================="
echo "Deep+Scrubbing Distribution by day:"
for date in `ceph pg dump | grep active | awk '{print $23}'`; do date +%A -d $date; done | sort | uniq -c
echo
echo "Deep+Scrubbing Distribution by hour:"
for date in `ceph pg dump | grep active | awk '{print $24}'`; do date +%H -d $date; done | sort | uniq -c
echo
echo "=============================="
echo "Scrubbing distribution by day:"
for date in `ceph pg dump | grep active | awk '{print $20}'`; do date +%A -d $date; done | sort | uniq -c
echo
echo "Scrubbing distribution per hour:"
for date in `ceph pg dump | grep active | awk '{print $21}'`; do date +%H -d $date; done | sort | uniq -c
